//-----------------------------------------------------------------------
// This file has been generated by stringres by Metallic Entertainment
// for further information go to http://www.metallic-entertainment.com
//-----------------------------------------------------------------------

#ifndef _INCLUDE_TRESOURCES_H
#define _INCLUDE_TRESOURCES_H

extern const char *default_face_shader_vert;
extern const char *default_face_shader_frag;
extern const char *cube_env_shader_vert;
extern const char *cube_env_shader_frag;
extern const char *point_shadow_shader_vert;
extern const char *point_shadow_shader_frag;
extern const char *point_shadow_blur_shader_vert;
extern const char *point_shadow_blur_shader_frag;
extern const char *directional_shadow_shader_vert;
extern const char *directional_shadow_shader_frag;
extern const char *directional_shadow_blur_shader_vert;
extern const char *directional_shadow_blur_shader_frag;

#endif