//-----------------------------------------------------------------------
// This file has been generated by stringres by Metallic Entertainment
// for further information go to http://www.metallic-entertainment.com
//-----------------------------------------------------------------------

#ifndef _INCLUDE_TRESOURCES_H
#define _INCLUDE_TRESOURCES_H

extern const char *geometry_pass_shader_vert;
extern const char *geometry_pass_shader_frag;
extern const char *light_pass_shader_vert;
extern const char *directional_lighting_shader_frag;
extern const char *point_lighting_shader_frag;
extern const char *ambient_lighting_shader_frag;
extern const char *ssao_lighting_shader_frag;
extern const char *cube_env_shader_vert;
extern const char *cube_env_shader_frag;
extern const char *point_shadow_shader_vert;
extern const char *point_shadow_shader_frag;
extern const char *point_shadow_blur_shader_vert;
extern const char *point_shadow_blur_shader_frag;
extern const char *directional_shadow_shader_vert;
extern const char *directional_shadow_shader_frag;
extern const char *directional_shadow_blur_shader_vert;
extern const char *directional_shadow_blur_shader_frag;
extern const char *post_process_shader_vert;
extern const char *post_process_shader_frag;
extern const char *ssao_shader_vert;
extern const char *ssao_shader_frag;
extern const char *ssao_blur_shader_vert;
extern const char *ssao_blur_shader_frag;
extern const char *color_shader_vert;
extern const char *color_shader_frag;
extern const char *fog_shader_vert;
extern const char *fog_shader_frag;
extern const char *cube_map_reflection_shader_vert;
extern const char *cube_map_reflection_shader_frag;

#endif